apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pixelfed.fullname" . }}
  labels:
    {{- include "pixelfed.labels" . | nindent 4 }}
type: Opaque
data:
  APP_KEY: "{{ randAlphaNum 32 | b64enc }}"
  DB_PASSWORD: "{{ .Values.mysql.auth.password | b64enc }}"
  MYSQL_PASSWORD: "{{ .Values.mysql.auth.password | b64enc }}"
  REDIS_PASSWORD: "{{ .Values.redis.password | b64enc }}"
{{- if .Values.pixelfed.smtp.enabled }}
  MAIL_PASSWORD: "{{ .Values.pixelfed.smtp.password | b64enc }}"
{{- end }}
